//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sasanRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sasanRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.sasanRes", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمودار.
        /// </summary>
        internal static string chart {
            get {
                return ResourceManager.GetString("chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد دانش آموزان کلاس.
        /// </summary>
        internal static string classcount {
            get {
                return ResourceManager.GetString("classcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کلاس.
        /// </summary>
        internal static string classnum {
            get {
                return ResourceManager.GetString("classnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش کلاس ها.
        /// </summary>
        internal static string classreports {
            get {
                return ResourceManager.GetString("classreports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد رهگیری.
        /// </summary>
        internal static string coderahgiri {
            get {
                return ResourceManager.GetString("coderahgiri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        internal static string desc {
            get {
                return ResourceManager.GetString("desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزییات.
        /// </summary>
        internal static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام پدر.
        /// </summary>
        internal static string fathername {
            get {
                return ResourceManager.GetString("fathername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        internal static string fname {
            get {
                return ResourceManager.GetString("fname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش مقاطع.
        /// </summary>
        internal static string gradereports {
            get {
                return ResourceManager.GetString("gradereports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        internal static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان درس.
        /// </summary>
        internal static string lessontitle {
            get {
                return ResourceManager.GetString("lessontitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        internal static string lname {
            get {
                return ResourceManager.GetString("lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ.
        /// </summary>
        internal static string mablagh {
            get {
                return ResourceManager.GetString("mablagh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to میانگین کل امتحان های کتبی دانش آموزان.
        /// </summary>
        internal static string mianginkatbi {
            get {
                return ResourceManager.GetString("mianginkatbi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to میانگین کل امتحان های شفاهی دانش آموزان.
        /// </summary>
        internal static string mianginshafahi {
            get {
                return ResourceManager.GetString("mianginshafahi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت ها.
        /// </summary>
        internal static string payments {
            get {
                return ResourceManager.GetString("payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد پاسخ به تمارین.
        /// </summary>
        internal static string percentamrinanswer {
            get {
                return ResourceManager.GetString("percentamrinanswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش.
        /// </summary>
        internal static string report {
            get {
                return ResourceManager.GetString("report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارشات.
        /// </summary>
        internal static string reports {
            get {
                return ResourceManager.GetString("reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره دانشجویی.
        /// </summary>
        internal static string stucode {
            get {
                return ResourceManager.GetString("stucode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش دانش آموزان.
        /// </summary>
        internal static string studentreports {
            get {
                return ResourceManager.GetString("studentreports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخچه ی پرداخت شهریه دانش آموزان.
        /// </summary>
        internal static string studentspaymenthistory {
            get {
                return ResourceManager.GetString("studentspaymenthistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد تمرین های داده شده.
        /// </summary>
        internal static string tamrincount {
            get {
                return ResourceManager.GetString("tamrincount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدرس.
        /// </summary>
        internal static string teacher {
            get {
                return ResourceManager.GetString("teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعت.
        /// </summary>
        internal static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
    }
}
