//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field
    {
        public Field()
        {
            this.StuRegisters = new HashSet<StuRegister>();
        }
    
        public int FieldID { get; set; }
        public string FieldTitle { get; set; }
    
        public virtual ICollection<StuRegister> StuRegisters { get; set; }
    }
}
