//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sessoin
    {
        public Sessoin()
        {
            this.Nomarats = new HashSet<Nomarat>();
            this.Presences = new HashSet<Presence>();
        }
    
        public int SessionID { get; set; }
        public string Date { get; set; }
        public Nullable<int> LGID { get; set; }
        public Nullable<int> SessionNum { get; set; }
    
        public virtual LessonGroup LessonGroup { get; set; }
        public virtual ICollection<Nomarat> Nomarats { get; set; }
        public virtual ICollection<Presence> Presences { get; set; }
    }
}
