//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAvgStuLessonsPerMonth
    {
        public Nullable<int> LGID { get; set; }
        public string LessonTitle { get; set; }
        public string mnth { get; set; }
        public Nullable<decimal> AvgNomre { get; set; }
        public int ID { get; set; }
        public string Title { get; set; }
        public string adad { get; set; }
        public string StudentCode { get; set; }
    }
}
