//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vJavabeTamrin
    {
        public int JavabID { get; set; }
        public Nullable<int> TamrinTamrinID { get; set; }
        public Nullable<int> Expr5 { get; set; }
        public string FilePath { get; set; }
        public string JavabeTamrinDescription { get; set; }
        public string SendingTime { get; set; }
        public string SendingDate { get; set; }
        public int TamrinID { get; set; }
        public string TamrinTitle { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string StartDate { get; set; }
        public string ExpirationDate { get; set; }
        public string Expr3 { get; set; }
        public int Expr2 { get; set; }
        public string Class { get; set; }
        public Nullable<int> LessonID { get; set; }
        public string TeacherCode { get; set; }
        public Nullable<int> GradeID { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> Time { get; set; }
        public Nullable<int> FieldID { get; set; }
        public string Year { get; set; }
        public string StudentCode { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public int OzviatOzviatID { get; set; }
        public Nullable<int> OzviatLGID { get; set; }
        public string OzviatStudentCode { get; set; }
        public Nullable<int> CGrade { get; set; }
    }
}
