//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSessoin
    {
        public string Date { get; set; }
        public string Class { get; set; }
        public int LGID { get; set; }
        public int SessionID { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> Time { get; set; }
        public string Year { get; set; }
        public string StudentCode { get; set; }
        public int OzviatID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> isMovajjah { get; set; }
        public string Description { get; set; }
        public Nullable<int> ExamType { get; set; }
        public string Nomre { get; set; }
        public Nullable<bool> Type { get; set; }
        public Nullable<int> NomrePercent { get; set; }
        public int NomreID { get; set; }
    }
}
