//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vStudentsInfo
    {
        public string StudentCode { get; set; }
        public string fullName { get; set; }
        public string FirstName { get; set; }
        public Nullable<int> CGrade { get; set; }
        public string gradeTitle { get; set; }
        public string stuClass { get; set; }
    }
}
